/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IInfoProvider = t.iface([], {
  "addProvider": t.func("void", t.param("provider", "IInfoService")),
  "retrieve": t.func("any", t.param("providers", t.union(t.array("string"), "null", "undefined"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  IInfoProvider,
};
export default exportedTypeSuite;
