/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IInfoService = t.iface([], {
  "name": "string",
  "retrieve": t.func("any"),
});

const exportedTypeSuite: t.ITypeSuite = {
  IInfoService,
};
export default exportedTypeSuite;
