/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IHealthService = t.iface([], {
  "status": t.func("any", t.param("providers", t.union(t.array("string"), "null"))),
});

const exportedTypeSuite: t.ITypeSuite = {
  IHealthService,
};
export default exportedTypeSuite;
