/**
 * This module was automatically generated by `ts-interface-builder`
 */
import * as t from "ts-interface-checker";
// tslint:disable:object-literal-key-quotes

export const IHealthServiceConfig = t.iface([], {
});

const exportedTypeSuite: t.ITypeSuite = {
  IHealthServiceConfig,
};
export default exportedTypeSuite;
